apiVersion: v1
kind: ConfigMap
metadata:
  name: logearn-minitor-service-dev-config
  namespace: logearn-dev
data:
  DEPLOYMENT_ENV: dev
  COPY_TRADE_ENABLE: 'true'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logearn-dev
  name: logearn-minitor-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logearn-minitor-service-dev
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: logearn-minitor-service-dev
    spec:
      nodeSelector:
        logearn_dev: 'true'
      containers:
        - name: logearn-minitor-service-dev
          image: __IMAGE__
          args: ["--spring.profiles.active=dev"]
          env:
            - name: JAVA_OPTS
              value: "-XX:PermSize=512M -XX:MaxPermSize=512M -Xms512M -Xmx512M"
          envFrom:
            - configMapRef:
                name: logearn-minitor-service-dev-config
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 600m
              memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: logearn-dev
  name: logearn-minitor-service-dev
spec:
  ports:
    - port: 9111
  selector:
    app: logearn-minitor-service-dev
  type: NodePort=