server:
  port: 9111
  servlet:
    context-path: /sb-admin
spring:
  jmx:
    enabled: true
  boot:
    admin:
      notify:
        jvm:
          enabled: true
        flybook:
          ignore-changes: ""
          webhook-url: https://open.feishu.cn/open-apis/bot/v2/hook/b791499e-ff2c-4b6c-abd5-5d1676173dad
      ui:
        title: Logearn 服务监控中心
        public-url: https://logearn.com
      client:
        instance:
          metadata:
            tags:
              environment: prod
          #要获取的client的端点信息
      probed-endpoints: health,env,metrics,httptrace:trace,threaddump:dump,jolokia,info,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents
      monitor: # 监控发送请求的超时时间
        default-timeout: 20000
#  security: # 设置账号密码
#    user:
#      name: logearn_admin
#      password: logearn_admin_2024
# 服务端点详细监控信息
management:
  trace:
    http:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always