name: Deploy to development environment

on:
  push:
    tags:
      - prod-v*

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Get short SHA
        id: slug
        run: |
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # maven缓存，不加的话每次都会去重新拉取，会影响速度
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 编译打包
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: Constansure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_URL: '${{ steps.login-ecr.outputs.registry }}/logearn-minitor-service:${{ steps.slug.outputs.tag }}'
        run: |
          docker build . --tag $IMAGE_URL
          docker push $IMAGE_URL

      - name: Patch Constansurations
        env:
          IMAGE_URL: '${{ steps.login-ecr.outputs.registry }}/logearn-minitor-service:${{ steps.slug.outputs.tag }}'
        run: |
          sed -i "s|__IMAGE__|$IMAGE_URL|g" deployments/prod-deployment.yaml

      # 安装 cli 工具
      - name: Setup AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master

      # 确认 AWS CLI 运行版本
      - run: aws --version
        shell: bash

      # 确认 AWS CLI 使用者的身份是否符合预期？
      - run: aws sts get-caller-identity
        shell: bash

      - name: deploy to cluster for logearn-minitor-service
        uses: TakumiHQ/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "v1.21.14"
        with:
          args: apply -f deployments/prod-deployment.yaml --v=9


      - name: verify deployment for logearn-minitor-service
        uses: TakumiHQ/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "v1.21.14"
        with:
          args: rollout status -n  logearn-prod deployments/logearn-minitor-service-prod
